export const quotationTemplate = {
  id: "quotation",
  type: "quotation",
  profileSchemaId: "quotation",
  name: "Quotation",
  fullName: "ใบเสนอราคา (Quotation)",
  logo: "/preview.webp",
  issuer: {
    name: "CREST ZENDO CO., LTD.",
    nameTh: "บริษัท เครสท์ เซนโด จำกัด",
    taxId: "0105558073755 (สำนักงานใหญ่)",
    address: "8/40 The Connect 37 Village, Soi Chang Air Utis 10 Yaek 1-2, Don Mueang, Don Mueang, Bangkok 10210",
    phone: "02-103-1861",
    website: "www.crestzendo.com",
    email: "info@crestzendo.com",
  },
  fields: [
    { id: "bill_to_company", sharedKey: "bill_to_company", label: "ชื่อบริษัทลูกค้า (Bill To / To)", type: "text", required: true },
    { id: "attn_name", sharedKey: "attn_name", label: "ผู้ติดต่อ (Attn.)", type: "text", required: true },
    { id: "end_user", sharedKey: "end_user", label: "End User", type: "text", required: false },
    { id: "subject", sharedKey: "subject", label: "หัวข้อเรื่อง (Subject)", type: "text", required: false },
    { id: "am_name", sharedKey: "am_name", label: "ชื่อ Account Manager (AM)", type: "text", required: true },
    { id: "am_phone", sharedKey: "am_phone", label: "เบอร์โทรศัพท์ AM", type: "text", required: false },
    { id: "price_validity", sharedKey: "price_validity", label: "ระยะเวลาการยืนราคา (Price Validity)", type: "text", required: false },
    { id: "delivery_term", sharedKey: "delivery_term", label: "เงื่อนไขส่งมอบ (Delivery Term)", type: "text", required: false },
    { id: "credit_term", sharedKey: "credit_term", label: "เงื่อนไขชำระเงิน (Credit Term)", type: "text", required: false },
  ],
  defaultLineItems: [
    {
      id: "item-1",
      title: "CDNetworks Annual Services",
      qty: 1,
      unitPrice: 204000,
      groups: [
        {
          id: "group-1",
          heading: "Application Shield Services",
          bullets: [
            { id: "b1", text: "Protected Top-Level-Domain up to 5, and Unlimited Sub-Domain", subBullets: [] },
            { id: "b2", text: "Dynamic Web Acceleration Platform Fee/month", subBullets: [] },
            { id: "b3", text: "Application Shield Platform Fee/month", subBullets: [] },
            { id: "b4", text: "Commit traffic up to 500Gbps/month", subBullets: [] },
            {
              id: "b5",
              text: "Cloud Security 2.0 Fee/month",
              subBullets: [
                { id: "sb1", text: "Web Application Firewall (WAF)" },
                { id: "sb2", text: "DDoS Protection" },
                { id: "sb3", text: "BOT Management" },
              ],
            },
            { id: "b6", text: "Contract Term: One (1) Year", subBullets: [] },
          ],
        },
        {
          id: "group-2",
          heading: "Onboarding Assistance & Advanced Customer Support",
          bullets: [
            { id: "b2-1", text: "New domain onboarding assistance", subBullets: [] },
            { id: "b2-2", text: "Security configuration assistance and customization", subBullets: [] },
            { id: "b2-3", text: "Security policies analysis", subBullets: [] },
            { id: "b2-4", text: "24/7/365 email/Group Chat and phone hotline support", subBullets: [] },
            { id: "b2-5", text: "Advanced 100% SLA Guarantee", subBullets: [] },
          ],
        },
        {
          id: "group-3",
          heading: "Web Application Firewall (WAF)",
          bullets: [
            { id: "b3-1", text: "Advanced Access Control", subBullets: [] },
            { id: "b3-2", text: "Advanced Rate Limiting", subBullets: [] },
            { id: "b3-3", text: "IP Repeated Violations", subBullets: [] },
            { id: "b3-4", text: "HTTP Protocol Validation", subBullets: [] },
            { id: "b3-5", text: "Built-in WAF Rules", subBullets: [] },
            { id: "b3-6", text: "OWASP Core Rulesets", subBullets: [] },
            { id: "b3-7", text: "Zero Day Protection", subBullets: [] },
            { id: "b3-8", text: "Flexible Response Actions", subBullets: [] },
            { id: "b3-9", text: "Rule template Management", subBullets: [] },
          ],
        },
        {
          id: "group-4",
          heading: "DDoS Protection",
          bullets: [
            { id: "b4-1", text: "Advance Access Control", subBullets: [] },
            { id: "b4-2", text: "Advance Rate Limiting", subBullets: [] },
            { id: "b4-3", text: "L3/L4 DDoS Mitigation", subBullets: [] },
            { id: "b4-4", text: "L7 DDoS Dashboard", subBullets: [] },
            { id: "b4-5", text: "Log & incident investigation tools_Basic", subBullets: [] },
            { id: "b4-6", text: "Custom Block Page", subBullets: [] },
            { id: "b4-7", text: "WAF Dashboard", subBullets: [] },
          ],
        },
        {
          id: "group-5",
          heading: "Present Protection Policies",
          bullets: [
            { id: "b5-1", text: "Present Protection Policies", subBullets: [] },
            { id: "b5-2", text: "Log & Incident Investigation Tools Basic", subBullets: [] },
            { id: "b5-3", text: "Deploy History", subBullets: [] },
          ],
        },
        {
          id: "group-6",
          heading: "BOT Management",
          bullets: [
            { id: "b6-1", text: "Transparent Challenges", subBullets: [] },
            { id: "b6-2", text: "Human Behavior Detection", subBullets: [] },
            { id: "b6-3", text: "Customized Actions", subBullets: [] },
            { id: "b6-4", text: "Advanced Rate Limiting", subBullets: [] },
            { id: "b6-5", text: "Visual Dashboard", subBullets: [] },
          ],
        },
        {
          id: "group-7",
          heading: "General Features",
          bullets: [
            { id: "b7-1", text: "Multiple Protocol support (HTTP/HTTPS/Websocket/HTTP2)", subBullets: [] },
            { id: "b7-2", text: "Email notification of Attack Event", subBullets: [] },
            { id: "b7-3", text: "Security Analysis and Basic Report", subBullets: [] },
          ],
        },
        {
          id: "group-8",
          heading: "Managed Service",
          bullets: [
            { id: "b8-1", text: "Service Level Agreement (SLA) 24x7x4", subBullets: [] },
            { id: "b8-2", text: "Level 2 Support", subBullets: [] },
            { id: "b8-3", text: "Unlimited Phone, email support", subBullets: [] },
            { id: "b8-4", text: "Implementation Service", subBullets: [] },
            { id: "b8-5", text: "Monthly Report", subBullets: [] },
          ],
        },
      ],
    },
  ],
};
