/**
 * 🎨 Dynamic Block-to-Canvas Synthesizer
 * Bridges block-based templates (e.g. system quotation, nda, contracts) to Fabric.js Canvas pages.
 * Ensures that any duplicated or block-based template renders rich, interactive canvas objects in Template Studio.
 */

const FONT_FAMILY = "'Noto Sans Thai', 'Noto Sans', sans-serif";

/**
 * Synthesizes Fabric canvas pages from a template's blocks or metadata.
 * @param {Object} template
 * @returns {Array<{ id: string, json: string }>}
 */
export function synthesizeCanvasPagesFromTemplate(template) {
  if (!template) return [];

  // If template already has valid pages with canvas objects, keep them
  if (Array.isArray(template.pages) && template.pages.length > 0) {
    const firstPage = template.pages[0];
    if (firstPage?.json) {
      try {
        const parsed = typeof firstPage.json === "string" ? JSON.parse(firstPage.json) : firstPage.json;
        if (Array.isArray(parsed?.objects) && parsed.objects.length > 0) {
          return template.pages;
        }
      } catch (e) {
        // Continue to synthesize if invalid json
      }
    }
  }

  const categoryId = (template.categoryId || "").toLowerCase();
  const templateId = (template.id || "").toLowerCase();
  const name = (template.name || "").toLowerCase();

  // 1. QUOTATION TEMPLATE
  if (categoryId === "quotation" || templateId.includes("quotation") || name.includes("เสนอราคา") || name.includes("quotation")) {
    return [
      {
        id: "page-1",
        json: JSON.stringify({
          version: "6.9.1",
          objects: [
            // ── 1. Top Decorative Green Wave Background (bg1.png) ──
            {
              type: "image",
              src: "/bg1.png",
              left: 0,
              top: 0,
              width: 1774,
              height: 887,
              scaleX: 794 / 1774,
              scaleY: 115 / 887,
              originX: "left",
              originY: "top",
              selectable: false,
              evented: false,
            },

            // ── 2. Crest Zendo Logo (quotation.png) ──
            {
              type: "image",
              src: "/quotation.png",
              left: 56,
              top: 22,
              width: 138,
              height: 90,
              scaleX: 62 / 90,
              scaleY: 62 / 90,
              originX: "left",
              originY: "top",
              selectable: true,
            },

            // ── 3. Company Header (4 Uniform Rows) ──
            {
              type: "textbox",
              left: 165,
              top: 24,
              width: 310,
              text: "CREST ZENDO CO., LTD.",
              fontSize: 12,
              fontWeight: "bold",
              fill: "#111827",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 165,
              top: 40,
              width: 310,
              text: "บริษัท เครสท์ เซนโด จำกัด",
              fontSize: 12,
              fontWeight: "bold",
              fill: "#111827",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 165,
              top: 57,
              width: 310,
              text: "The Connect 37, 8/40 Soi Chang Akat Uthit 10 Yaek 1-2, Donmueang, Bangkok 10210",
              fontSize: 8.5,
              fill: "#4B5563",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 165,
              top: 72,
              width: 140,
              text: "เลขประจำตัวผู้เสียภาษีอากร:",
              fontSize: 9.5,
              fill: "#4B5563",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "rect",
              left: 308,
              top: 72,
              width: 84,
              height: 16,
              rx: 8,
              ry: 8,
              fill: "#0F4C35",
            },
            {
              type: "textbox",
              left: 308,
              top: 73,
              width: 84,
              text: "0105558073755",
              fontSize: 9,
              fontWeight: "bold",
              fill: "#FFFFFF",
              textAlign: "center",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 396,
              top: 72,
              width: 80,
              text: "(สำนักงานใหญ่)",
              fontSize: 9.5,
              fill: "#4B5563",
              fontFamily: FONT_FAMILY,
            },

            // ── 4. Document Title: QUOTATION (Right Aligned) ──
            {
              type: "textbox",
              left: 480,
              top: 30,
              width: 258,
              text: "QUOTATION",
              textAlign: "right",
              fontSize: 32,
              fontWeight: "900",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },

            // ── 5. Two-Column Metadata Grid (5 Symmetric Rows) ──
            // Left Column (Bill To)
            {
              type: "textbox",
              left: 56,
              top: 104,
              width: 62,
              text: "To",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 120,
              top: 104,
              width: 260,
              text: "{{customer_name}}",
              fontSize: 11,
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 125,
              width: 62,
              text: "Attn.",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 120,
              top: 125,
              width: 260,
              text: "{{contact_person}}",
              fontSize: 11,
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 146,
              width: 62,
              text: "End User",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 120,
              top: 146,
              width: 260,
              text: "{{end_user}}",
              fontSize: 11,
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 167,
              width: 62,
              text: "Subject",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 120,
              top: 167,
              width: 260,
              text: "{{subject}}",
              fontSize: 11,
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 188,
              width: 62,
              text: "AM",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 120,
              top: 188,
              width: 260,
              text: "{{am_name}}",
              fontSize: 11,
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },

            // Right Column (Metadata)
            {
              type: "textbox",
              left: 450,
              top: 104,
              width: 110,
              text: "Quotation No.",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "rect",
              left: 588,
              top: 102,
              width: 114,
              height: 20,
              rx: 4,
              ry: 4,
              fill: "#0F4C35",
            },
            {
              type: "textbox",
              left: 588,
              top: 104,
              width: 114,
              text: "{{quotation_no}}",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#FFFFFF",
              textAlign: "center",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "rect",
              left: 708,
              top: 102,
              width: 30,
              height: 20,
              rx: 4,
              ry: 4,
              fill: "#0F4C35",
            },
            {
              type: "textbox",
              left: 708,
              top: 104,
              width: 30,
              text: "01",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#FFFFFF",
              textAlign: "center",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 450,
              top: 125,
              width: 110,
              text: "Quotation Date",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 570,
              top: 125,
              width: 168,
              text: "{{date}}",
              fontSize: 11,
              fill: "#1F2937",
              textAlign: "right",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 450,
              top: 146,
              width: 110,
              text: "Price Validity",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 570,
              top: 146,
              width: 168,
              text: "30 days",
              fontSize: 11,
              fill: "#1F2937",
              textAlign: "right",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 450,
              top: 167,
              width: 110,
              text: "Delivery Term",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 570,
              top: 167,
              width: 168,
              text: "7 days",
              fontSize: 11,
              fill: "#1F2937",
              textAlign: "right",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 450,
              top: 188,
              width: 110,
              text: "Credit Term",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 570,
              top: 188,
              width: 168,
              text: "30 days",
              fontSize: 11,
              fill: "#1F2937",
              textAlign: "right",
              fontFamily: FONT_FAMILY,
            },

            // ── 6. Authentic 5-Column Pricing Table (DocTable) ──
            {
              type: "DocTable",
              isDocTable: true,
              left: 56,
              top: 220,
              originX: "left",
              originY: "top",
              scaleX: 1,
              scaleY: 1,
              angle: 0,
              docTableData: {
                width: 682,
                themeColor: "#0F4C35",
                vatRate: 7,
                cols: [
                  { title: "PRODUCT CODE", width: 105, align: "left" },
                  { title: "DESCRIPTION", width: 330, align: "left" },
                  { title: "QTY", width: 40, align: "center" },
                  { title: "PRICE", width: 105, align: "right" },
                  { title: "AMOUNT", width: 102, align: "right" },
                ],
                items: [
                  {
                    no: "CZ-001",
                    desc: "บริการจัดทำและพัฒนาระบบเอกสารดิจิทัล Enterprise",
                    qty: 1,
                    price: 45000,
                  },
                  {
                    no: "CZ-002",
                    desc: "แพ็กเกจพื้นที่จัดเก็บข้อมูลบนคลาวด์และระบบรักษาความปลอดภัย",
                    qty: 1,
                    price: 15000,
                  },
                  {
                    no: "CZ-003",
                    desc: "บริการฝึกอบรมการใช้งานและสนับสนุนทางเทคนิครายปี (SLA 99.9%)",
                    qty: 1,
                    price: 12000,
                  },
                ],
              },
            },

            // ── 7. Remarks Section ──
            {
              type: "textbox",
              left: 56,
              top: 435,
              width: 120,
              text: "Remarks :",
              fontSize: 10.5,
              fontWeight: "bold",
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 66,
              top: 454,
              width: 672,
              text: "• Payment: Annually\n• กำหนดยืนราคา 30 วันนับจากวันที่ออกใบเสนอราคา\n• ราคานี้ยังไม่รวมภาษีมูลค่าเพิ่ม 7% (VAT Excluded)",
              fontSize: 10,
              lineHeight: 1.45,
              fill: "#DC2626",
              fontFamily: FONT_FAMILY,
            },

            // ── 8. Bottom 3-Column Summary & Signatures Block ──
            // Box 1: Best regards, (Issuer Info)
            {
              type: "rect",
              left: 56,
              top: 860,
              width: 216,
              height: 180,
              fill: "#FFFFFF",
              stroke: "#E5E7EB",
              strokeWidth: 1,
              rx: 6,
              ry: 6,
            },
            {
              type: "textbox",
              left: 68,
              top: 870,
              width: 192,
              text: "Best regards,",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "line",
              x1: 0,
              y1: 0,
              x2: 192,
              y2: 0,
              left: 68,
              top: 890,
              stroke: "#F3F4F6",
              strokeWidth: 1,
            },
            {
              type: "textbox",
              left: 68,
              top: 900,
              width: 192,
              text: "Narin Rattanavajij (PoP)\nManaging Director\ncontact@crestzendo.com\n+6682-44-686-95",
              fontSize: 10,
              lineHeight: 1.5,
              fill: "#374151",
              fontFamily: FONT_FAMILY,
            },

            // Box 2: Customer Approval
            {
              type: "rect",
              left: 286,
              top: 860,
              width: 216,
              height: 180,
              fill: "#FFFFFF",
              stroke: "#E5E7EB",
              strokeWidth: 1,
              rx: 6,
              ry: 6,
            },
            {
              type: "textbox",
              left: 298,
              top: 870,
              width: 192,
              text: "Customer Approval",
              fontSize: 11,
              fontWeight: "bold",
              fill: "#0F4C35",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "line",
              x1: 0,
              y1: 0,
              x2: 192,
              y2: 0,
              left: 298,
              top: 890,
              stroke: "#F3F4F6",
              strokeWidth: 1,
            },
            {
              type: "textbox",
              left: 298,
              top: 920,
              width: 192,
              text: "ลงชื่อ ................................................\n( {{customer_signatory_name}} )\nวันที่: ...... / ...... / ......",
              fontSize: 10,
              textAlign: "center",
              lineHeight: 1.7,
              fill: "#4B5563",
              fontFamily: FONT_FAMILY,
            },

            // Box 3: PRICE SUMMARY
            {
              type: "rect",
              left: 516,
              top: 860,
              width: 222,
              height: 180,
              fill: "#F9FAFB",
              stroke: "#E5E7EB",
              strokeWidth: 1,
              rx: 6,
              ry: 6,
            },
            {
              type: "rect",
              left: 516,
              top: 860,
              width: 222,
              height: 26,
              fill: "#0F4C35",
              rx: 6,
              ry: 6,
            },
            {
              type: "textbox",
              left: 516,
              top: 866,
              width: 222,
              text: "PRICE SUMMARY",
              fontSize: 10.5,
              fontWeight: "bold",
              fill: "#FFFFFF",
              textAlign: "center",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 526,
              top: 896,
              width: 202,
              text: "SUBTOTAL:                    72,000.00 THB\nSpecial Discount:                   0.00 THB\nTOTAL (After Disc.):     72,000.00 THB\nVAT (7%):                        5,040.00 THB\nGRAND TOTAL:            77,040.00 THB",
              fontSize: 10,
              lineHeight: 1.6,
              fill: "#1F2937",
              fontFamily: FONT_FAMILY,
            },
          ],
        }),
      },
    ];
  }

  // 2. NDA / CONTRACT TEMPLATE
  const isNdaTemplate = categoryId === "nda"
    || templateId === "nda"
    || templateId.includes("-nda-")
    || templateId.startsWith("nda-")
    || name.includes("ไม่เปิดเผยข้อมูล")
    || name.includes("nda");
  if (isNdaTemplate) {
    const ndaObjects = [
            {
              type: "textbox",
              left: 56,
              top: 56,
              width: 682,
              text: "หนังสือสัญญาไม่เปิดเผยข้อมูล\nNON-DISCLOSURE AGREEMENT (NDA)",
              fontSize: 18,
              fontWeight: "bold",
              fill: "#1E293B",
              textAlign: "center",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "line",
              left: 56,
              top: 115,
              width: 682,
              stroke: "#E2E8F0",
              strokeWidth: 1.5,
            },
            {
              type: "textbox",
              left: 56,
              top: 130,
              width: 682,
              text: "สัญญานี้ทำขึ้น ณ {{contract_location}} เมื่อวันที่ {{contract_date_day}} {{contract_date_month}} {{contract_date_year}}\nระหว่าง {{our_company_name}} (\"ผู้เปิดเผยข้อมูล\") ฝ่ายหนึ่ง\nกับ {{counterparty_name}} สำนักงานตั้งอยู่เลขที่ {{counterparty_address}} (\"ผู้รับข้อมูล\") อีกฝ่ายหนึ่ง",
              fontSize: 11.5,
              lineHeight: 1.6,
              fill: "#334155",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 240,
              width: 682,
              text: "ข้อ 1. นิยามข้อมูลความลับ\nข้อมูลความลับหมายถึง ข้อมูลทางธุรกิจ เทคโนโลยี แผนการตลาด รหัสต้นฉบับ (Source Code) รายชื่อลูกค้า หรือข้อมูลอื่นใดที่เปิดเผยไม่ว่าจะในรูปแบบลายลักษณ์อักษร วาจา หรืออิเล็กทรอนิกส์",
              fontSize: 11.5,
              lineHeight: 1.6,
              fill: "#1E293B",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 340,
              width: 682,
              text: "ข้อ 2. ข้อกำหนดการรักษาความลับ\nผู้รับข้อมูลตกลงที่จะเก็บรักษาข้อมูลความลับไว้เป็นความลับอย่างเคร่งครัด และจะไม่เปิดเผยต่อบุคคลภายนอก เว้นแต่จะได้รับความยินยอมเป็นลายลักษณ์อักษรจากผู้เปิดเผยข้อมูล",
              fontSize: 11.5,
              lineHeight: 1.6,
              fill: "#1E293B",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 680,
              width: 300,
              text: "ลงนามผู้เปิดเผยข้อมูล:\n\n\n........................................................\n( {{our_signatory_name}} )\n{{our_signatory_position}}",
              fontSize: 11,
              fill: "#475569",
              lineHeight: 1.5,
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 438,
              top: 680,
              width: 300,
              text: "ลงนามผู้รับข้อมูล:\n\n\n........................................................\n( {{counterparty_signatory_name}} )\n{{counterparty_signatory_position}}",
              fontSize: 11,
              fill: "#475569",
              lineHeight: 1.5,
              fontFamily: FONT_FAMILY,
            },
    ];

    // Keep the editable NDA structure aligned with the four-page document renderer.
    const pageGroups = [
      ndaObjects.slice(0, 3),
      [ndaObjects[3]],
      [ndaObjects[4]],
      ndaObjects.slice(5),
    ];
    return pageGroups.map((objects, index) => ({
      id: `page-${index + 1}`,
      json: JSON.stringify({ version: "6.9.1", objects }),
    }));
  }

  // 3. NOTIFICATION LETTER TEMPLATE
  if (categoryId === "notification" || templateId.includes("notification") || name.includes("หนังสือแจ้ง")) {
    return [
      {
        id: "page-1",
        json: JSON.stringify({
          version: "6.9.1",
          objects: [
            {
              type: "textbox",
              left: 56,
              top: 56,
              width: 682,
              text: "บริษัท เครสท์ เซนโด จำกัด\nCREST ZENDO CO., LTD.",
              fontSize: 16,
              fontWeight: "bold",
              fill: "#1E293B",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "line",
              left: 56,
              top: 115,
              width: 682,
              stroke: "#E2E8F0",
              strokeWidth: 1.5,
            },
            {
              type: "textbox",
              left: 56,
              top: 135,
              width: 682,
              text: "หนังสือแจ้งเปลี่ยนแปลงที่ตั้งสำนักงานใหญ่\nNOTICE OF HEAD OFFICE RELOCATION",
              fontSize: 16,
              fontWeight: "bold",
              textAlign: "center",
              fill: "#1E40AF",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 56,
              top: 200,
              width: 682,
              text: "เรียน: ท่านคู่ค้า ลูกค้า และพันธมิตรทางธุรกิจทุกท่าน\nเรื่อง: ขอแจ้งเปลี่ยนแปลงสถานที่ตั้งสำนักงานใหญ่แห่งใหม่",
              fontSize: 12,
              lineHeight: 1.6,
              fill: "#334155",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "rect",
              left: 56,
              top: 280,
              width: 682,
              height: 120,
              fill: "#F8FAFC",
              stroke: "#CBD5E1",
              strokeWidth: 1,
              rx: 8,
              ry: 8,
            },
            {
              type: "textbox",
              left: 76,
              top: 295,
              width: 642,
              text: "ที่อยู่สำนักงานใหญ่เดิม:\n{{prev_address_th}}\n\nที่อยู่สำนักงานใหญ่แห่งใหม่ (มีผลตั้งแต่วันที่ {{effective_date_th}}):\n{{new_address_th}}",
              fontSize: 11.5,
              lineHeight: 1.5,
              fill: "#1E293B",
              fontFamily: FONT_FAMILY,
            },
            {
              type: "textbox",
              left: 400,
              top: 550,
              width: 338,
              text: "ขอแสดงความนับถืออย่างสูง\n\n\n........................................................\n( {{signatory_name}} )\n{{signatory_title}}\nบริษัท เครสท์ เซนโด จำกัด",
              fontSize: 11,
              textAlign: "center",
              lineHeight: 1.5,
              fill: "#475569",
              fontFamily: FONT_FAMILY,
            },
          ],
        }),
      },
    ];
  }

  // 4. GENERIC CONTRACT / AGREEMENT TEMPLATE (Default Fallback)
  return [
    {
      id: "page-1",
      json: JSON.stringify({
        version: "6.9.1",
        objects: [
          {
            type: "textbox",
            left: 56,
            top: 56,
            width: 682,
            text: template.name || "สัญญาและข้อตกลง (Agreement)",
            fontSize: 18,
            fontWeight: "bold",
            fill: "#1E293B",
            textAlign: "center",
            fontFamily: FONT_FAMILY,
          },
          {
            type: "line",
            left: 56,
            top: 105,
            width: 682,
            stroke: "#E2E8F0",
            strokeWidth: 1.5,
          },
          {
            type: "textbox",
            left: 56,
            top: 130,
            width: 682,
            text: "สัญญานี้ทำขึ้นเมื่อวันที่ {{contract_date_day}} {{contract_date_month}} {{contract_date_year}}\nระหว่าง {{our_company_name}} กับ {{counterparty_name}}",
            fontSize: 12,
            lineHeight: 1.6,
            fill: "#334155",
            fontFamily: FONT_FAMILY,
          },
          {
            type: "textbox",
            left: 56,
            top: 650,
            width: 300,
            text: "ลงนามฝ่ายที่หนึ่ง:\n\n\n........................................................\n( {{our_signatory_name}} )",
            fontSize: 11,
            fill: "#475569",
            lineHeight: 1.5,
            fontFamily: FONT_FAMILY,
          },
          {
            type: "textbox",
            left: 438,
            top: 650,
            width: 300,
            text: "ลงนามฝ่ายที่สอง:\n\n\n........................................................\n( {{counterparty_signatory_name}} )",
            fontSize: 11,
            fill: "#475569",
            lineHeight: 1.5,
            fontFamily: FONT_FAMILY,
          },
        ],
      }),
    },
  ];
}
